MASCOTS = {
    'new-orleans': 'Privateers',
    'st-bonaventure': 'Bonnies',
    'middle-tennessee': 'Blue Raiders',
    'saint-louis': 'Billikens',
    'cincinnati': 'Bearcats',
    'houston': 'Cougars',
    'grambling': 'Tigers',
    'santa-clara': 'Broncos',
    'southern-utah': 'Thunderbirds',
    'wagner': 'Seahawks',
    'saint-josephs': 'Hawks',
    'auburn': 'Tigers',
    'illinois-state': 'Redbirds',
    'troy': 'Trojans',
    'miami-oh': 'RedHawks',
    'austin-peay': 'Governors',
    'savannah-state': 'Tigers',
    'morehead-state': 'Eagles',
    'campbell': 'Fighting Camels',
    'milwaukee': 'Panthers',
    'nevada': 'Wolf Pack',
    'mercer': 'Bears',
    'maine': 'Black Bears',
    'drexel': 'Dragons',
    'green-bay': 'Phoenix',
    'texas-tech': 'Red Raiders',
    'oral-roberts': 'Golden Eagles',
    'east-carolina': 'Pirates',
    'wyoming': 'Cowboys',
    'san-diego': 'Toreros',
    'minnesota': 'Golden Gophers',
    'denver': 'Pioneers',
    'jacksonville': 'Dolphins',
    'boston-university': 'Terriers',
    'chicago-state': 'Cougars',
    'southern-california': 'Trojans',
    'dartmouth': 'Big Green',
    'maryland': 'Terrapins',
    'rice': 'Owls',
    'wake-forest': 'Demon Deacons',
    'texas-christian': 'Horned Frogs',
    'oakland': 'Golden Grizzlies',
    'brown': 'Bears',
    'presbyterian': 'Blue Hose',
    'northern-colorado': 'Bears',
    'iowa': 'Hawkeyes',
    'tulsa': 'Golden Hurricane',
    'western-illinois': 'Leathernecks',
    'michigan': 'Wolverines',
    'incarnate-word': 'Cardinals',
    'belmont': 'Bruins',
    'georgia-southern': 'Eagles',
    'southeast-missouri-state': 'Redhawks',
    'james-madison': 'Dukes',
    'norfolk-state': 'Spartans',
    'west-virginia': 'Mountaineers',
    'furman': 'Paladins',
    'northern-kentucky': 'Norse',
    'depaul': 'Blue Demons',
    'nevada-las-vegas': 'Runnin&#39; Rebels',
    'akron': 'Zips',
    'boston-college': 'Eagles',
    'bryant': 'Bulldogs',
    'syracuse': 'Orange',
    'texas-san-antonio': 'Roadrunners',
    'northwestern': 'Wildcats',
    'utah-valley': 'Wolverines',
    'bethune-cookman': 'Wildcats',
    'george-washington': 'Colonials',
    'fresno-state': 'Bulldogs',
    'northwestern-state': 'Demons',
    'purdue': 'Boilermakers',
    'mississippi-state': 'Bulldogs',
    'hawaii': 'Rainbow Warriors',
    'drake': 'Bulldogs',
    'kansas-state': 'Wildcats',
    'cal-poly': 'Mustangs',
    'baylor': 'Bears',
    'north-carolina': 'Tar Heels',
    'idaho': 'Vandals',
    'georgia-state': 'Panthers',
    'yale': 'Bulldogs',
    'central-arkansas': 'Bears',
    'ohio': 'Bobcats',
    'george-mason': 'Patriots',
    'southern-illinois': 'Salukis',
    'california-riverside': 'Highlanders',
    'creighton': 'Bluejays',
    'colorado-state': 'Rams',
    'alabama': 'Crimson Tide',
    'youngstown-state': 'Penguins',
    'duquesne': 'Dukes',
    'cornell': 'Big Red',
    'san-francisco': 'Dons',
    'stephen-f-austin': 'Lumberjacks',
    'south-carolina-upstate': 'Spartans',
    'saint-peters': 'Peacocks',
    'appalachian-state': 'Mountaineers',
    'georgia-tech': 'Yellow Jackets',
    'pacific': 'Tigers',
    'bradley': 'Braves',
    'lehigh': 'Mountain Hawks',
    'wofford': 'Terriers',
    'southern-mississippi': 'Golden Eagles',
    'long-island-university': 'Blackbirds',
    'navy': 'Midshipmen',
    'notre-dame': 'Fighting Irish',
    'portland': 'Pilots',
    'oregon-state': 'Beavers',
    'massachusetts-lowell': 'River Hawks',
    'colgate': 'Raiders',
    'florida-gulf-coast': 'Eagles',
    'villanova': 'Wildcats',
    'kennesaw-state': 'Owls',
    'ipfw': 'Mastodons',
    'oklahoma-state': 'Cowboys',
    'brigham-young': 'Cougars',
    'oklahoma': 'Sooners',
    'delaware': 'Fightin&#39; Blue Hens',
    'florida-international': 'Golden Panthers',
    'liberty': 'Flames',
    'richmond': 'Spiders',
    'providence': 'Friars',
    'south-florida': 'Bulls',
    'quinnipiac': 'Bobcats',
    'arkansas': 'Razorbacks',
    'toledo': 'Rockets',
    'temple': 'Owls',
    'california-santa-barbara': 'Gauchos',
    'south-carolina': 'Gamecocks',
    'alcorn-state': 'Braves',
    'lamar': 'Cardinals',
    'arizona': 'Wildcats',
    'wisconsin': 'Badgers',
    'holy-cross': 'Crusaders',
    'louisiana-state': 'Tigers',
    'tennessee-state': 'Tigers',
    'old-dominion': 'Monarchs',
    'new-mexico': 'Lobos',
    'vanderbilt': 'Commodores',
    'william-mary': 'Tribe',
    'detroit-mercy': 'Titans',
    'portland-state': 'Vikings',
    'iowa-state': 'Cyclones',
    'harvard': 'Crimson',
    'california': 'Golden Bears',
    'south-dakota': 'Coyotes',
    'florida-am': 'Rattlers',
    'cal-state-northridge': 'Matadors',
    'texas-state': 'Bobcats',
    'rutgers': 'Scarlet Knights',
    'sacramento-state': 'Hornets',
    'murray-state': 'Racers',
    'iupui': 'Jaguars',
    'north-dakota-state': 'Bison',
    'bucknell': 'Bison',
    'siena': 'Saints',
    'albany-ny': 'Great Danes',
    'eastern-michigan': 'Eagles',
    'texas-pan-american': 'Vaqueros',
    'southeastern-louisiana': 'Lions',
    'western-michigan': 'Broncos',
    'army': 'Black Knights',
    'florida': 'Gators',
    'st-francis-ny': 'Terriers',
    'fairleigh-dickinson': 'Knights',
    'north-carolina-at': 'Aggies',
    'rhode-island': 'Rams',
    'north-carolina-central': 'Eagles',
    'prairie-view': 'Panthers',
    'missouri-kansas-city': 'Kangaroos',
    'florida-atlantic': 'Owls',
    'south-dakota-state': 'Jackrabbits',
    'washington-state': 'Cougars',
    'north-carolina-greensboro': 'Spartans',
    'gardner-webb': 'Runnin&#39; Bulldogs',
    'binghamton': 'Bearcats',
    'duke': 'Blue Devils',
    'hampton': 'Pirates',
    'canisius': 'Golden Griffins',
    'fordham': 'Rams',
    'colorado': 'Buffaloes',
    'air-force': 'Falcons',
    'loyola-marymount': 'Lions',
    'miami-fl': 'Hurricanes',
    'east-tennessee-state': 'Buccaneers',
    'northeastern': 'Huskies',
    'washington': 'Huskies',
    'weber-state': 'Wildcats',
    'tennessee': 'Volunteers',
    'san-diego-state': 'Aztecs',
    'wright-state': 'Raiders',
    'marquette': 'Golden Eagles',
    'arkansas-state': 'Red Wolves',
    'mississippi-valley-state': 'Delta Devils',
    'central-connecticut-state': 'Blue Devils',
    'cleveland-state': 'Vikings',
    'north-carolina-wilmington': 'Seahawks',
    'virginia-commonwealth': 'Rams',
    'mississippi': 'Rebels',
    'towson': 'Tigers',
    'lipscomb': 'Bisons',
    'howard': 'Bison',
    'western-kentucky': 'Hilltoppers',
    'marist': 'Red Foxes',
    'northern-iowa': 'Panthers',
    'ucla': 'Bruins',
    'fairfield': 'Stags',
    'arizona-state': 'Sun Devils',
    'abilene-christian': 'Wildcats',
    'robert-morris': 'Colonials',
    'ball-state': 'Cardinals',
    'stetson': 'Hatters',
    'butler': 'Bulldogs',
    'indiana': 'Hoosiers',
    'new-mexico-state': 'Aggies',
    'evansville': 'Aces',
    'long-beach-state': '49ers',
    'stanford': 'Cardinal',
    'indiana-state': 'Sycamores',
    'georgetown': 'Hoyas',
    'gonzaga': 'Bulldogs',
    'new-hampshire': 'Wildcats',
    'eastern-illinois': 'Panthers',
    'jacksonville-state': 'Gamecocks',
    'michigan-state': 'Spartans',
    'samford': 'Bulldogs',
    'wichita-state': 'Shockers',
    'charleston-southern': 'Buccaneers',
    'nicholls-state': 'Colonels',
    'oregon': 'Ducks',
    'north-texas': 'Mean Green',
    'eastern-kentucky': 'Colonels',
    'hartford': 'Hawks',
    'northern-arizona': 'Lumberjacks',
    'maryland-baltimore-county': 'Retrievers',
    'louisiana-monroe': 'Warhawks',
    'coppin-state': 'Eagles',
    'memphis': 'Tigers',
    'hofstra': 'Pride',
    'montana-state': 'Bobcats',
    'georgia': 'Bulldogs',
    'boise-state': 'Broncos',
    'northern-illinois': 'Huskies',
    'texas-southern': 'Tigers',
    'princeton': 'Tigers',
    'marshall': 'Thundering Herd',
    'houston-baptist': 'Huskies',
    'missouri': 'Tigers',
    'central-florida': 'Knights',
    'kentucky': 'Wildcats',
    'arkansas-little-rock': 'Trojans',
    'seton-hall': 'Pirates',
    'idaho-state': 'Bengals',
    'nebraska': 'Cornhuskers',
    'texas': 'Longhorns',
    'longwood': 'Lancers',
    'clemson': 'Tigers',
    'citadel': 'Bulldogs',
    'ohio-state': 'Buckeyes',
    'texas-am-corpus-christi': 'Islanders',
    'virginia-tech': 'Hokies',
    'charlotte': '49ers',
    'maryland-eastern-shore': 'Hawks',
    'winthrop': 'Eagles',
    'south-carolina-state': 'Bulldogs',
    'missouri-state': 'Bears',
    'penn-state': 'Nittany Lions',
    'valparaiso': 'Crusaders',
    'southern-methodist': 'Mustangs',
    'elon': 'Phoenix',
    'sacred-heart': 'Pioneers',
    'iona': 'Gaels',
    'niagara': 'Purple Eagles',
    'eastern-washington': 'Eagles',
    'louisiana-tech': 'Bulldogs',
    'north-carolina-asheville': 'Bulldogs',
    'utah-state': 'Aggies',
    'seattle': 'Redhawks',
    'kent-state': 'Golden Flashes',
    'coastal-carolina': 'Chanticleers',
    'western-carolina': 'Catamounts',
    'delaware-state': 'Hornets',
    'jackson-state': 'Tigers',
    'california-irvine': 'Anteaters',
    'arkansas-pine-bluff': 'Golden Lions',
    'njit': 'Highlanders',
    'bowling-green-state': 'Falcons',
    'illinois': 'Fighting Illini',
    'vermont': 'Catamounts',
    'louisville': 'Cardinals',
    'sam-houston-state': 'Bearkats',
    'stony-brook': 'Seawolves',
    'north-dakota': 'Fighting Hawks',
    'tennessee-tech': 'Golden Eagles',
    'rider': 'Broncs',
    'davidson': 'Wildcats',
    'mcneese-state': 'Cowboys',
    'saint-francis-pa': 'Red Flash',
    'high-point': 'Panthers',
    'columbia': 'Lions',
    'monmouth': 'Hawks',
    'san-jose-state': 'Spartans',
    'utah': 'Runnin&#39; Utes',
    'kansas': 'Jayhawks',
    'alabama-state': 'Hornets',
    'cal-state-fullerton': 'Titans',
    'central-michigan': 'Chippewas',
    'virginia': 'Cavaliers',
    'pittsburgh': 'Panthers',
    'pepperdine': 'Waves',
    'montana': 'Grizzlies',
    'massachusetts': 'Minutemen',
    'mount-st-marys': 'Mountaineers',
    'alabama-birmingham': 'Blazers',
    'radford': 'Highlanders',
    'south-alabama': 'Jaguars',
    'virginia-military-institute': 'Keydets',
    'chattanooga': 'Mocs',
    'morgan-state': 'Bears',
    'tulane': 'Green Wave',
    'la-salle': 'Explorers',
    'pennsylvania': 'Quakers',
    'manhattan': 'Jaspers',
    'north-florida': 'Ospreys',
    'connecticut': 'Huskies',
    'florida-state': 'Seminoles',
    'saint-marys-ca': 'Gaels',
    'california-davis': 'Aggies',
    'lafayette': 'Leopards',
    'st-johns-ny': 'Red Storm',
    'dayton': 'Flyers',
    'grand-canyon': 'Antelopes',
    'xavier': 'Musketeers',
    'texas-am': 'Aggies',
    'buffalo': 'Bulls',
    'alabama-am': 'Bulldogs',
    'texas-arlington': 'Mavericks',
    'north-carolina-state': 'Wolfpack',
    'illinois-chicago': 'Flames',
    'texas-el-paso': 'Miners',
    'american': 'Eagles',
    'southern': 'Jaguars',
    'college-of-charleston': 'Cougars',
    'loyola-md': 'Greyhounds',
    'louisiana-lafayette': 'Ragin Cajuns',
    'nebraska-omaha': 'Mavericks',
    'southern-illinois-edwardsville': 'Cougars',
    'loyola-il': 'Ramblers',
    'tennessee-martin': 'Skyhawks',
    'cal-state-bakersfield': 'Roadrunners',
    'california-baptist': 'Lancers',
    'north-alabama': 'Lions'
}
