TEAMS = {
    "Abilene Christian": "abilene-christian",
    "Air Force": "air-force",
    "Akron": "akron",
    "Alabama A&M": "alabama-am",
    "Alabama-Birmingham": "alabama-birmingham",
    "Alabama State": "alabama-state",
    "Alabama": "alabama",
    "Albany (NY)": "albany-ny",
    "Alcorn State": "alcorn-state",
    "American": "american",
    "Appalachian State": "appalachian-state",
    "Arizona State": "arizona-state",
    "Arizona": "arizona",
    "Arkansas-Little Rock": "arkansas-little-rock",
    "Arkansas-Pine Bluff": "arkansas-pine-bluff",
    "Arkansas State": "arkansas-state",
    "Arkansas": "arkansas",
    "Army": "army",
    "Auburn": "auburn",
    "Austin Peay": "austin-peay",
    "Ball State": "ball-state",
    "Baylor": "baylor",
    "Belmont": "belmont",
    "Bethune-Cookman": "bethune-cookman",
    "Binghamton": "binghamton",
    "Boise State": "boise-state",
    "Boston College": "boston-college",
    "Boston University": "boston-university",
    "Bowling Green State": "bowling-green-state",
    "Bradley": "bradley",
    "Brigham Young": "brigham-young",
    "Brown": "brown",
    "Bryant": "bryant",
    "Bucknell": "bucknell",
    "Buffalo": "buffalo",
    "Butler": "butler",
    "Cal Poly": "cal-poly",
    "Cal State Bakersfield": "cal-state-bakersfield",
    "Cal State Fullerton": "cal-state-fullerton",
    "Cal State Northridge": "cal-state-northridge",
    "UC-Davis": "california-davis",
    "UC-Irvine": "california-irvine",
    "UC-Riverside": "california-riverside",
    "UC-Santa Barbara": "california-santa-barbara",
    "University of California": "california",
    "Campbell": "campbell",
    "Canisius": "canisius",
    "Central Arkansas": "central-arkansas",
    "Central Connecticut State": "central-connecticut-state",
    "Central Florida": "central-florida",
    "Central Michigan": "central-michigan",
    "Charleston Southern": "charleston-southern",
    "Charlotte": "charlotte",
    "Chattanooga": "chattanooga",
    "Chicago State": "chicago-state",
    "Cincinnati": "cincinnati",
    "Citadel": "citadel",
    "Clemson": "clemson",
    "Cleveland State": "cleveland-state",
    "Coastal Carolina": "coastal-carolina",
    "Colgate": "colgate",
    "College of Charleston": "college-of-charleston",
    "Colorado State": "colorado-state",
    "Colorado": "colorado",
    "Columbia": "columbia",
    "Connecticut": "connecticut",
    "Coppin State": "coppin-state",
    "Cornell": "cornell",
    "Creighton": "creighton",
    "Dartmouth": "dartmouth",
    "Davidson": "davidson",
    "Dayton": "dayton",
    "Delaware State": "delaware-state",
    "Delaware": "delaware",
    "Denver": "denver",
    "DePaul": "depaul",
    "Detroit Mercy": "detroit-mercy",
    "Drake": "drake",
    "Drexel": "drexel",
    "Duke": "duke",
    "Duquesne": "duquesne",
    "East Carolina": "east-carolina",
    "East Tennessee State": "east-tennessee-state",
    "Eastern Illinois": "eastern-illinois",
    "Eastern Kentucky": "eastern-kentucky",
    "Eastern Michigan": "eastern-michigan",
    "Eastern Washington": "eastern-washington",
    "Elon": "elon",
    "Evansville": "evansville",
    "Fairfield": "fairfield",
    "Fairleigh Dickinson": "fairleigh-dickinson",
    "Florida A&M": "florida-am",
    "Florida Atlantic": "florida-atlantic",
    "Florida Gulf Coast": "florida-gulf-coast",
    "Florida International": "florida-international",
    "Florida State": "florida-state",
    "Florida": "florida",
    "Fordham": "fordham",
    "Fresno State": "fresno-state",
    "Furman": "furman",
    "Gardner-Webb": "gardner-webb",
    "George Mason": "george-mason",
    "George Washington": "george-washington",
    "Georgetown": "georgetown",
    "Georgia Southern": "georgia-southern",
    "Georgia State": "georgia-state",
    "Georgia Tech": "georgia-tech",
    "Georgia": "georgia",
    "Gonzaga": "gonzaga",
    "Grambling": "grambling",
    "Grand Canyon": "grand-canyon",
    "Green Bay": "green-bay",
    "Hampton": "hampton",
    "Hartford": "hartford",
    "Harvard": "harvard",
    "Hawaii": "hawaii",
    "High Point": "high-point",
    "Hofstra": "hofstra",
    "Holy Cross": "holy-cross",
    "Houston Baptist": "houston-baptist",
    "Houston": "houston",
    "Howard": "howard",
    "Idaho State": "idaho-state",
    "Idaho": "idaho",
    "Illinois-Chicago": "illinois-chicago",
    "Illinois State": "illinois-state",
    "Illinois": "illinois",
    "Incarnate Word": "incarnate-word",
    "Indiana State": "indiana-state",
    "Indiana": "indiana",
    "Iona": "iona",
    "Iowa State": "iowa-state",
    "Iowa": "iowa",
    "IPFW": "ipfw",
    "IUPUI": "iupui",
    "Jackson State": "jackson-state",
    "Jacksonville State": "jacksonville-state",
    "Jacksonville": "jacksonville",
    "James Madison": "james-madison",
    "Kansas State": "kansas-state",
    "Kansas": "kansas",
    "Kennesaw State": "kennesaw-state",
    "Kent State": "kent-state",
    "Kentucky": "kentucky",
    "La Salle": "la-salle",
    "Lafayette": "lafayette",
    "Lamar": "lamar",
    "Lehigh": "lehigh",
    "Liberty": "liberty",
    "Lipscomb": "lipscomb",
    "Long Beach State": "long-beach-state",
    "Long Island University": "long-island-university",
    "Longwood": "longwood",
    "Louisiana-Lafayette": "louisiana-lafayette",
    "Louisiana-Monroe": "louisiana-monroe",
    "Louisiana State": "louisiana-state",
    "Louisiana Tech": "louisiana-tech",
    "Louisville": "louisville",
    "Loyola (IL)": "loyola-il",
    "Loyola Marymount": "loyola-marymount",
    "Loyola (MD)": "loyola-md",
    "Maine": "maine",
    "Manhattan": "manhattan",
    "Marist": "marist",
    "Marquette": "marquette",
    "Marshall": "marshall",
    "Maryland-Baltimore County": "maryland-baltimore-county",
    "Maryland-Eastern Shore": "maryland-eastern-shore",
    "Maryland": "maryland",
    "Massachusetts-Lowell": "massachusetts-lowell",
    "Massachusetts": "massachusetts",
    "McNeese State": "mcneese-state",
    "Memphis": "memphis",
    "Mercer": "mercer",
    "Miami (FL)": "miami-fl",
    "Miami (OH)": "miami-oh",
    "Michigan State": "michigan-state",
    "Michigan": "michigan",
    "Middle Tennessee": "middle-tennessee",
    "Milwaukee": "milwaukee",
    "Minnesota": "minnesota",
    "Mississippi State": "mississippi-state",
    "Mississippi Valley State": "mississippi-valley-state",
    "Mississippi": "mississippi",
    "Missouri-Kansas City": "missouri-kansas-city",
    "Missouri State": "missouri-state",
    "Missouri": "missouri",
    "Monmouth": "monmouth",
    "Montana State": "montana-state",
    "Montana": "montana",
    "Morehead State": "morehead-state",
    "Morgan State": "morgan-state",
    "Mount St. Mary's": "mount-st-marys",
    "Murray State": "murray-state",
    "Navy": "navy",
    "Nebraska-Omaha": "nebraska-omaha",
    "Nebraska": "nebraska",
    "Nevada-Las Vegas": "nevada-las-vegas",
    "Nevada": "nevada",
    "New Hampshire": "new-hampshire",
    "New Mexico State": "new-mexico-state",
    "New Mexico": "new-mexico",
    "New Orleans": "new-orleans",
    "Niagara": "niagara",
    "Nicholls State": "nicholls-state",
    "NJIT": "njit",
    "Norfolk State": "norfolk-state",
    "North Carolina-Asheville": "north-carolina-asheville",
    "North Carolina A&T": "north-carolina-at",
    "North Carolina Central": "north-carolina-central",
    "North Carolina-Greensboro": "north-carolina-greensboro",
    "North Carolina State": "north-carolina-state",
    "North Carolina-Wilmington": "north-carolina-wilmington",
    "North Carolina": "north-carolina",
    "North Dakota State": "north-dakota-state",
    "North Dakota": "north-dakota",
    "North Florida": "north-florida",
    "North Texas": "north-texas",
    "Northeastern": "northeastern",
    "Northern Arizona": "northern-arizona",
    "Northern Colorado": "northern-colorado",
    "Northern Illinois": "northern-illinois",
    "Northern Iowa": "northern-iowa",
    "Northern Kentucky": "northern-kentucky",
    "Northwestern State": "northwestern-state",
    "Northwestern": "northwestern",
    "Notre Dame": "notre-dame",
    "Oakland": "oakland",
    "Ohio State": "ohio-state",
    "Ohio": "ohio",
    "Oklahoma State": "oklahoma-state",
    "Oklahoma": "oklahoma",
    "Old Dominion": "old-dominion",
    "Oral Roberts": "oral-roberts",
    "Oregon State": "oregon-state",
    "Oregon": "oregon",
    "Pacific": "pacific",
    "Penn State": "penn-state",
    "Pennsylvania": "pennsylvania",
    "Pepperdine": "pepperdine",
    "Pittsburgh": "pittsburgh",
    "Portland State": "portland-state",
    "Portland": "portland",
    "Prairie View": "prairie-view",
    "Presbyterian": "presbyterian",
    "Princeton": "princeton",
    "Providence": "providence",
    "Purdue": "purdue",
    "Quinnipiac": "quinnipiac",
    "Radford": "radford",
    "Rhode Island": "rhode-island",
    "Rice": "rice",
    "Richmond": "richmond",
    "Rider": "rider",
    "Robert Morris": "robert-morris",
    "Rutgers": "rutgers",
    "Sacramento State": "sacramento-state",
    "Sacred Heart": "sacred-heart",
    "Saint Francis (PA)": "saint-francis-pa",
    "Saint Joseph's": "saint-josephs",
    "Saint Louis": "saint-louis",
    "Saint Mary's (CA)": "saint-marys-ca",
    "Saint Peter's": "saint-peters",
    "Sam Houston State": "sam-houston-state",
    "Samford": "samford",
    "San Diego State": "san-diego-state",
    "San Diego": "san-diego",
    "San Francisco": "san-francisco",
    "San Jose State": "san-jose-state",
    "Santa Clara": "santa-clara",
    "Savannah State": "savannah-state",
    "Seattle": "seattle",
    "Seton Hall": "seton-hall",
    "Siena": "siena",
    "South Alabama": "south-alabama",
    "South Carolina State": "south-carolina-state",
    "South Carolina Upstate": "south-carolina-upstate",
    "South Carolina": "south-carolina",
    "South Dakota State": "south-dakota-state",
    "South Dakota": "south-dakota",
    "South Florida": "south-florida",
    "Southeast Missouri State": "southeast-missouri-state",
    "Southeastern Louisiana": "southeastern-louisiana",
    "Southern California": "southern-california",
    "SIU Edwardsville": "southern-illinois-edwardsville",
    "Southern Illinois": "southern-illinois",
    "Southern Methodist": "southern-methodist",
    "Southern Mississippi": "southern-mississippi",
    "Southern Utah": "southern-utah",
    "Southern": "southern",
    "St. Bonaventure": "st-bonaventure",
    "St. Francis (NY)": "st-francis-ny",
    "St. John's (NY)": "st-johns-ny",
    "Stanford": "stanford",
    "Stephen F. Austin": "stephen-f-austin",
    "Stetson": "stetson",
    "Stony Brook": "stony-brook",
    "Syracuse": "syracuse",
    "Temple": "temple",
    "Tennessee-Martin": "tennessee-martin",
    "Tennessee State": "tennessee-state",
    "Tennessee Tech": "tennessee-tech",
    "Tennessee": "tennessee",
    "Texas A&M-Corpus Christi": "texas-am-corpus-christi",
    "Texas A&M": "texas-am",
    "Texas-Arlington": "texas-arlington",
    "Texas Christian": "texas-christian",
    "Texas-El Paso": "texas-el-paso",
    "Texas-Rio Grande Valley": "texas-pan-american",
    "Texas-San Antonio": "texas-san-antonio",
    "Texas Southern": "texas-southern",
    "Texas State": "texas-state",
    "Texas Tech": "texas-tech",
    "Texas": "texas",
    "Toledo": "toledo",
    "Towson": "towson",
    "Troy": "troy",
    "Tulane": "tulane",
    "Tulsa": "tulsa",
    "UCLA": "ucla",
    "Utah State": "utah-state",
    "Utah Valley": "utah-valley",
    "Utah": "utah",
    "Valparaiso": "valparaiso",
    "Vanderbilt": "vanderbilt",
    "Vermont": "vermont",
    "Villanova": "villanova",
    "Virginia Commonwealth": "virginia-commonwealth",
    "VMI": "virginia-military-institute",
    "Virginia Tech": "virginia-tech",
    "Virginia": "virginia",
    "Wagner": "wagner",
    "Wake Forest": "wake-forest",
    "Washington State": "washington-state",
    "Washington": "washington",
    "Weber State": "weber-state",
    "West Virginia": "west-virginia",
    "Western Carolina": "western-carolina",
    "Western Illinois": "western-illinois",
    "Western Kentucky": "western-kentucky",
    "Western Michigan": "western-michigan",
    "Wichita State": "wichita-state",
    "William & Mary": "william-mary",
    "Winthrop": "winthrop",
    "Wisconsin": "wisconsin",
    "Wofford": "wofford",
    "Wright State": "wright-state",
    "Wyoming": "wyoming",
    "Xavier": "xavier",
    "Yale": "yale",
    "Youngstown State": "youngstown-state",
}
