name: Sanity Checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy dataset from latest Docker container
      run: |
        # In order to copy the dataset file from the latest image, a container needs to
        # be run with a volume pointing to the local directory and the dataset copied to
        # the attached volume.
        docker run --rm -v $(pwd):/opt/mount --rm --entrypoint cp \
          roclark/clarktech-ncaab-predictor /app/dataset.pkl \
          /opt/mount/dataset.pkl
        sudo chown $(whoami):$(whoami) dataset.pkl
    - name: Run daily simulation
      run: |
        python run-simulator.py --skip-save-to-mongodb daily-simulation
        
    - name: Run sanity check on matchup
      run: |
        # Run a comparison between a traditionally strong team (Duke) and a
        # traditionally weaker team (Delaware State) and verify the stronger team
        # is projected to win in a matchup between the two. These teams are picked
        # purely on their recent performances over the past decade, and is not based
        # on any biases or other means.
        #
        # Check that "Duke" shows up twice in the output, indicating that they are
        # the projected winner.
        python run-simulator.py --skip-save-to-mongodb matchup duke delaware-state \
          | grep -i "duke.*duke"
